### ISSUE TITLE
Reduce structural breaks between the new and the old FAOSTAT series in 1990-1999

### ISSUE THREAD

**Issue by carola-f** [SWS-Methodology/faoswsProduction#197]
The module does not suit those situations where there are few protected values and those few are available in recent years. See for example Bhutan, Other vegetables. 

The module must use old 1990-1998 data, on a conditional basis: 
• If there are more than 3 protected values in the 1990-1998 period, keep only the protected values in the imputation process
• If there are fewer than 3 protected values in the 1990-1998, keep all the 9 terms in the imputation process regardless of their flags. 

A similar conditional constraint on the first terms of the series existed but was removed when we decided to use (E,f) records as part of the imputations. The assumption was that there would be sufficient protected records to have a smooth transition between old and new imputed values. The assumption is not valid for the whole dataset.

**Comment by mkao006** [comment]
As I have already elaborated in previous email exchange, the removal of this implementation by Josh was not based on any assumption, rather, it was because the practice is bad. In addition, this creates more problem than it resolves.

I would suggest to run the imputation model on a longer time series, say starting from 1980 but only replace previous imputation from 1990. This will resolve any structural break problem while not introducing any additional problems. Ideally, we should run the imputation on the complete time series.

**Comment by carola-f** [comment]
The module is running and replacing imputations starting in 1990. Tests to extend the time series to 1980 were not successful due to the low number of basic data points and issues with the flags. 
Data series reconciliation in 1990 will be carried out, if at all, at a later stage and independently from the module.
